name: myapp
description: "A new Flutter project."
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.20.0
  google_maps_flutter: ^2.6.1
  flutter_map: ^7.0.2
  flutter_polyline_points: ^2.1.0
  location: ^6.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/slideview/
    - assets/logo/
    - assets/images/
   

# Suggested code may be subject to a license. Learn more: ~LicenseLog:2141102426.
